import type { ScenarioSeed } from '@/types';

export const scenarioSeeds: ScenarioSeed[] = [
  {
    id: 'ASK-A-001',
    title: 'Flightline Fragmentation Casualty After Missile Warning',
    section: 'A_field_reaction_triage_incident_response',
    threat: 'missile_attack',
    difficulty: 'intermediate',
    patients: 1,
    objectives: [
      'scene_safety',
      'hemorrhage_control',
      'airway_breathing_assessment',
      'evacuation_request',
    ],
  },
  {
    id: 'ASK-A-002',
    title: 'Drone Strike Near Logistics Yard With Multiple Walking Wounded',
    section: 'A_field_reaction_triage_incident_response',
    threat: 'drone_attack',
    difficulty: 'advanced',
    patients: 5,
    objectives: ['triage_sort', 'resource_prioritization', 'secondary_hazard_awareness'],
  },
  {
    id: 'ASK-B-001',
    title: 'Snowstorm Transport Delay With Deteriorating Blast Casualty',
    section: 'B_transport',
    threat: 'cold_weather_transport',
    difficulty: 'advanced',
    patients: 1,
    objectives: ['reassessment', 'hypothermia_prevention', 'handoff', 'route_decision'],
  },
  {
    id: 'ASK-C-001',
    title: 'Mass Casualty Patient Tracking During Comms Degradation',
    section: 'C_patient_administration',
    threat: 'missile_attack',
    difficulty: 'expert',
    patients: 12,
    objectives: [
      'temporary_identifiers',
      'status_tracking',
      'privacy_boundary',
      'command_update',
    ],
  },
  {
    id: 'ASK-D-001',
    title: 'Clinic Receives Blast Patient With Confusion And Chest Pain',
    section: 'D_clinical',
    threat: 'missile_attack',
    difficulty: 'advanced',
    patients: 1,
    objectives: ['differential', 'orders', 'deterioration_recognition', 'escalation'],
  },
  {
    id: 'ASK-E-001',
    title: 'Radiology Prioritization During MCI',
    section: 'E_radiology',
    threat: 'earthquake',
    difficulty: 'advanced',
    patients: 6,
    objectives: ['modality_priority', 'critical_findings_report', 'flow_control'],
  },
  {
    id: 'ASK-F-001',
    title: 'Lab Critical Values During Crush Injury Surge',
    section: 'F_lab',
    threat: 'earthquake',
    difficulty: 'expert',
    patients: 8,
    objectives: ['specimen_priority', 'critical_notification', 'result_tracking'],
  },
  {
    id: 'ASK-G-001',
    title: 'Pharmacy Allergy Conflict During Mass Casualty',
    section: 'G_pharmacy',
    threat: 'cbrne_suspected',
    difficulty: 'advanced',
    patients: 4,
    objectives: ['allergy_check', 'inventory_priority', 'medication_safety'],
  },
  {
    id: 'ASK-H-001',
    title: 'OR Queue Triage After Blast Event',
    section: 'H_surgery',
    threat: 'missile_attack',
    difficulty: 'expert',
    patients: 4,
    objectives: ['operative_priority', 'preop_handoff', 'resource_allocation'],
  },
  {
    id: 'ASK-I-001',
    title: 'MCC/UCC Casualty Flow Under Base-Wide Degraded Communications',
    section: 'I_mcc_ucc',
    threat: 'tsunami_earthquake',
    difficulty: 'expert',
    patients: 20,
    objectives: [
      'common_operating_picture',
      'section_capacity',
      'transport_coordination',
      'leadership_update',
    ],
  },
];

export const sectionLabels: Record<string, string> = {
  A_field_reaction_triage_incident_response: 'Field / Triage / Incident Response',
  B_transport: 'Transport',
  C_patient_administration: 'Patient Administration',
  D_clinical: 'Clinical',
  E_radiology: 'Radiology',
  F_lab: 'Lab',
  G_pharmacy: 'Pharmacy',
  H_surgery: 'Surgery',
  I_mcc_ucc: 'MCC / UCC',
};

export const roleLabels: Record<string, string> = {
  all_service_member: 'All Service Member',
  combat_lifesaver: 'Combat Lifesaver',
  medic_or_technician: 'Medic / Technician',
  nurse: 'Nurse',
  provider: 'Provider',
  admin_staff: 'Patient Administration',
  lab_tech: 'Lab Technician',
  radiology_tech: 'Radiology Technician',
  pharmacist: 'Pharmacist',
  mcc_ucc_controller: 'MCC / UCC Controller',
};

export const roleSections: Record<string, string[]> = {
  all_service_member: ['A_field_reaction_triage_incident_response'],
  combat_lifesaver: ['A_field_reaction_triage_incident_response', 'B_transport'],
  medic_or_technician: [
    'A_field_reaction_triage_incident_response',
    'B_transport',
    'D_clinical',
  ],
  nurse: ['D_clinical', 'B_transport', 'I_mcc_ucc'],
  provider: ['D_clinical', 'E_radiology', 'F_lab', 'G_pharmacy', 'H_surgery'],
  admin_staff: ['C_patient_administration', 'I_mcc_ucc'],
  lab_tech: ['F_lab'],
  radiology_tech: ['E_radiology'],
  pharmacist: ['G_pharmacy'],
  mcc_ucc_controller: ['I_mcc_ucc'],
};
