import ScenarioContracts

#print axioms ScenarioContracts.generated_content_cannot_define_clinical_rule
#print axioms ScenarioContracts.generated_content_cannot_define_scoring_truth
#print axioms ScenarioContracts.generated_content_cannot_define_physiology
#print axioms ScenarioContracts.supporting_evidence_cannot_define_clinical_rule
#print axioms ScenarioContracts.supporting_evidence_cannot_define_scoring_truth
#print axioms ScenarioContracts.capability_inclusion_reflexive
#print axioms ScenarioContracts.capability_inclusion_transitive
#print axioms ScenarioContracts.admitted_claim_has_identity
#print axioms ScenarioContracts.admitted_claim_has_entailment
#print axioms ScenarioContracts.admitted_claim_has_contradiction_clearance
#print axioms ScenarioContracts.admitted_claim_has_human_review
#print axioms ScenarioContracts.admitted_claim_has_authority_permission
#print axioms ScenarioContracts.admitted_import_has_integrity
#print axioms ScenarioContracts.admitted_import_clears_public_boundary
#print axioms ScenarioContracts.admitted_import_preserves_authority
#print axioms ScenarioContracts.admitted_import_resolves_references
#print axioms ScenarioContracts.admitted_import_is_staging_only
#print axioms ScenarioContracts.staged_content_cannot_activate
#print axioms ScenarioContracts.activated_content_has_compatibility
#print axioms ScenarioContracts.activated_content_has_independent_check
#print axioms ScenarioContracts.activated_content_has_human_review
#print axioms ScenarioContracts.activated_content_preserves_authority
