import ScenarioContracts

#print axioms ScenarioContracts.facility_operational_transition_preserves_clinical
#print axioms ScenarioContracts.facility_operational_action_has_no_source_binding
#print axioms ScenarioContracts.facility_operational_action_has_zero_clinical_points
#print axioms ScenarioContracts.facility_wit_transition_preserves_clinical_score
#print axioms ScenarioContracts.facility_wit_observation_has_no_clinical_directive
#print axioms ScenarioContracts.facility_hidden_findings_before_diagnostics_are_empty
#print axioms ScenarioContracts.facility_diagnostics_ready_reveals_exact_hidden_findings
#print axioms ScenarioContracts.facility_timeout_event_maps_to_timeout_terminal
#print axioms ScenarioContracts.facility_unsafe_event_maps_to_failed_terminal
#print axioms ScenarioContracts.facility_handoff_event_maps_to_completed_terminal
#print axioms ScenarioContracts.facility_production_training_prohibits_patient_care
#print axioms ScenarioContracts.facility_operational_replay_preserves_clinical
