import ScenarioContracts

#print axioms ScenarioContracts.decision_operational_transition_preserves_clinical
#print axioms ScenarioContracts.decision_learner_projection_ignores_instructor_score
#print axioms ScenarioContracts.decision_learner_projection_ignores_provenance
#print axioms ScenarioContracts.decision_unadjudicated_treatment_is_blocked
#print axioms ScenarioContracts.decision_missing_scope_blocks_treatment
#print axioms ScenarioContracts.decision_missing_eligibility_blocks_treatment
#print axioms ScenarioContracts.decision_missing_source_attestation_blocks_treatment
#print axioms ScenarioContracts.decision_absent_order_blocks_result
#print axioms ScenarioContracts.decision_queued_order_blocks_result
#print axioms ScenarioContracts.decision_completed_order_allows_result
#print axioms ScenarioContracts.decision_world_event_independent_of_action_identity
#print axioms ScenarioContracts.decision_handoff_without_ack_is_blocked
#print axioms ScenarioContracts.decision_handoff_without_questions_is_blocked
#print axioms ScenarioContracts.decision_handoff_without_sender_confirmation_is_blocked
#print axioms ScenarioContracts.decision_complete_closed_loop_handoff_transfers
#print axioms ScenarioContracts.decision_operational_replay_preserves_clinical
#print axioms ScenarioContracts.decision_training_prohibits_patient_care
