import ScenarioContracts.Basic
import ScenarioContracts.Route
import ScenarioContracts.Origin
import ScenarioContracts.Certificate

import ScenarioContracts.ContentRegistry
import ScenarioContracts.FacilityArrival
import ScenarioContracts.FacilityDecisionIntegrity
set_option autoImplicit false
