/* AUTO-GENERATED by scripts/build_facility_arrival_bindings.py. DO NOT EDIT. */
export const FACILITY_CONTENT_REGISTRY_ROOT = '9db5b82df90426da8c1543b9ef67464dec59aff90d9731a5be26fff83f621841' as const;
export const FACILITY_TEMPLATE_RECORD_SHA256 = '6eeb1fbea265617816c0fc0a74854673fe5395e1ef74d619e0913f89211afc57' as const;
export const FACILITY_SCENARIO_SOURCE_SHA256 = '22cccf6addc345deeceb79547d51bae0202b5382c327c69fd314754875b09a45' as const;
export const FACILITY_SCENARIO_SOURCE_HASH_MODE = 'canonical_utf8_lf_v1' as const;
export const FACILITY_SOURCE_SCENARIO_PROJECTION_SHA256 = 'b5562e64b4847d7bc47afc9fcc1e917aeee3268dddee3134bd2c3129266d5636' as const;
