/* AUTO-GENERATED by scripts/compile_facility_arrival_spec.py. DO NOT EDIT. */
import type { FacilityArrivalSpec } from './types';

export const FACILITY_ARRIVAL_SPEC_SHA256 = 'a13ee903414743d971edb1fbb53b2f624defc59a995cfd88235040766c0e54f8' as const;
export const FACILITY_ARRIVAL_SPEC = {
  "actions": [
    {
      "action_id": "receive_handoff",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 45,
      "knowledge_grants": {
        "clinic_nurse": [
          "field_handoff_reconciled"
        ],
        "receiving_provider": [
          "field_handoff_reconciled"
        ],
        "wit_observer": [
          "handoff_observed"
        ]
      },
      "label": "Receive casualty and reconcile the field handoff",
      "origin": "operational_workflow",
      "phase_after": "reception",
      "prerequisites": [],
      "repeatable": false,
      "required_event_ids": [
        "prearrival_notice"
      ],
      "source_action_id": null,
      "terminal_effect": null,
      "wit_category": "continuity"
    },
    {
      "action_id": "primary_assessment",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 90,
      "knowledge_grants": {
        "clinic_nurse": [
          "primary_assessment_complete"
        ],
        "receiving_provider": [
          "primary_assessment_complete"
        ],
        "wit_observer": [
          "assessment_sequence_observed"
        ]
      },
      "label": "Perform primary assessment",
      "origin": "source_template",
      "phase_after": "assessment",
      "prerequisites": [
        "receive_handoff"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": "primary_assessment",
      "terminal_effect": null,
      "wit_category": "assessment"
    },
    {
      "action_id": "monitor_vitals",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 30,
      "knowledge_grants": {
        "clinic_nurse": [
          "monitoring_established"
        ],
        "receiving_provider": [
          "monitoring_established"
        ],
        "wit_observer": [
          "monitoring_observed"
        ]
      },
      "label": "Establish continuous monitoring",
      "origin": "source_template",
      "phase_after": "assessment",
      "prerequisites": [
        "primary_assessment"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": "monitor_vitals",
      "terminal_effect": null,
      "wit_category": "monitoring"
    },
    {
      "action_id": "differential",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 60,
      "knowledge_grants": {
        "receiving_provider": [
          "working_differential_documented"
        ],
        "wit_observer": [
          "differential_documentation_observed"
        ]
      },
      "label": "Document differential diagnosis",
      "origin": "source_template",
      "phase_after": "assessment",
      "prerequisites": [
        "primary_assessment"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": "differential",
      "terminal_effect": null,
      "wit_category": "clinical_process"
    },
    {
      "action_id": "order_imaging",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 30,
      "knowledge_grants": {
        "clinic_nurse": [
          "imaging_ordered"
        ],
        "diagnostics_tech": [
          "imaging_ordered"
        ],
        "receiving_provider": [
          "imaging_ordered"
        ],
        "wit_observer": [
          "imaging_coordination_observed"
        ]
      },
      "label": "Order chest imaging",
      "origin": "source_template",
      "phase_after": "diagnostics_pending",
      "prerequisites": [
        "primary_assessment"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": "order_imaging",
      "terminal_effect": null,
      "wit_category": "diagnostics"
    },
    {
      "action_id": "order_labs",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 30,
      "knowledge_grants": {
        "clinic_nurse": [
          "labs_ordered"
        ],
        "diagnostics_tech": [
          "labs_ordered"
        ],
        "receiving_provider": [
          "labs_ordered"
        ],
        "wit_observer": [
          "laboratory_coordination_observed"
        ]
      },
      "label": "Order relevant labs",
      "origin": "source_template",
      "phase_after": "diagnostics_pending",
      "prerequisites": [
        "primary_assessment"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": "order_labs",
      "terminal_effect": null,
      "wit_category": "diagnostics"
    },
    {
      "action_id": "pain_management",
      "clinical_detail_policy": "NO_GENERATED_DRUG_DOSE_OR_ROUTE",
      "duration_mode": "fixed",
      "duration_seconds": 30,
      "knowledge_grants": {
        "clinic_nurse": [
          "pain_objective_addressed"
        ],
        "receiving_provider": [
          "pain_objective_addressed"
        ],
        "wit_observer": [
          "pain_objective_observed"
        ]
      },
      "label": "Address source-defined pain-management objective",
      "origin": "source_template",
      "phase_after": "diagnostics_pending",
      "prerequisites": [
        "primary_assessment"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": "pain_management",
      "terminal_effect": null,
      "wit_category": "source_objective"
    },
    {
      "action_id": "confirm_surge_roles",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 30,
      "knowledge_grants": {
        "clinic_nurse": [
          "surge_roles_confirmed"
        ],
        "receiving_provider": [
          "surge_roles_confirmed"
        ],
        "wit_observer": [
          "surge_role_confirmation_observed"
        ]
      },
      "label": "Acknowledge the surge notice and confirm receiving-team roles",
      "origin": "operational_workflow",
      "phase_after": "diagnostics_pending",
      "prerequisites": [
        "receive_handoff"
      ],
      "repeatable": false,
      "required_event_ids": [
        "second_casualty_inbound"
      ],
      "source_action_id": null,
      "terminal_effect": null,
      "wit_category": "surge_response"
    },
    {
      "action_id": "documentation",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 45,
      "knowledge_grants": {
        "clinic_nurse": [
          "documentation_complete"
        ],
        "receiving_provider": [
          "documentation_complete"
        ],
        "wit_observer": [
          "documentation_observed"
        ]
      },
      "label": "Document findings and plan",
      "origin": "source_template",
      "phase_after": "diagnostics_pending",
      "prerequisites": [
        "primary_assessment"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": "documentation",
      "terminal_effect": null,
      "wit_category": "documentation"
    },
    {
      "action_id": "wait_for_diagnostics",
      "clinical_detail_policy": null,
      "duration_mode": "until_diagnostics",
      "duration_seconds": 0,
      "knowledge_grants": {
        "receiving_provider": [
          "diagnostic_event_awaited"
        ],
        "wit_observer": [
          "diagnostic_timing_observed"
        ]
      },
      "label": "Advance to the next scheduled diagnostic event",
      "origin": "operational_workflow",
      "phase_after": "diagnostics_pending",
      "prerequisites": [
        "order_imaging",
        "order_labs"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": null,
      "terminal_effect": null,
      "wit_category": "timing"
    },
    {
      "action_id": "review_diagnostics",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 60,
      "knowledge_grants": {
        "clinic_nurse": [
          "diagnostics_reviewed"
        ],
        "receiving_provider": [
          "diagnostics_reviewed"
        ],
        "wit_observer": [
          "reassessment_observed"
        ]
      },
      "label": "Review returned results and reassess the casualty",
      "origin": "operational_workflow",
      "phase_after": "results_review",
      "prerequisites": [
        "wait_for_diagnostics"
      ],
      "repeatable": false,
      "required_event_ids": [
        "diagnostics_ready"
      ],
      "source_action_id": null,
      "terminal_effect": null,
      "wit_category": "reassessment"
    },
    {
      "action_id": "escalation",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 60,
      "knowledge_grants": {
        "clinic_nurse": [
          "disposition_escalated"
        ],
        "receiving_provider": [
          "disposition_escalated"
        ],
        "wit_observer": [
          "escalation_observed"
        ]
      },
      "label": "Escalate disposition / consult",
      "origin": "source_template",
      "phase_after": "disposition",
      "prerequisites": [
        "review_diagnostics"
      ],
      "repeatable": false,
      "required_event_ids": [
        "diagnostics_ready"
      ],
      "source_action_id": "escalation",
      "terminal_effect": null,
      "wit_category": "escalation"
    },
    {
      "action_id": "complete_handoff",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 60,
      "knowledge_grants": {
        "clinic_nurse": [
          "handoff_complete"
        ],
        "receiving_provider": [
          "handoff_complete"
        ],
        "wit_observer": [
          "handoff_closure_observed"
        ]
      },
      "label": "Complete the receiving handoff to the next level of care",
      "origin": "operational_workflow",
      "phase_after": "complete",
      "prerequisites": [
        "escalation",
        "documentation",
        "confirm_surge_roles"
      ],
      "repeatable": false,
      "required_event_ids": [
        "diagnostics_ready"
      ],
      "source_action_id": null,
      "terminal_effect": "completed",
      "wit_category": "handoff"
    },
    {
      "action_id": "wait_60",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 60,
      "knowledge_grants": {},
      "label": "Wait 60 seconds",
      "origin": "operational_workflow",
      "phase_after": null,
      "prerequisites": [],
      "repeatable": true,
      "required_event_ids": [
        "prearrival_notice"
      ],
      "source_action_id": null,
      "terminal_effect": null,
      "wit_category": "delay"
    },
    {
      "action_id": "discharge_without_workup",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 10,
      "knowledge_grants": {
        "wit_observer": [
          "unsafe_discharge_observed"
        ]
      },
      "label": "Discharge without adequate workup",
      "origin": "source_template",
      "phase_after": "complete",
      "prerequisites": [
        "receive_handoff"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": "discharge_without_workup",
      "terminal_effect": "failed",
      "wit_category": "unsafe_action"
    },
    {
      "action_id": "remove_tourniquet",
      "clinical_detail_policy": null,
      "duration_mode": "fixed",
      "duration_seconds": 10,
      "knowledge_grants": {
        "wit_observer": [
          "unsafe_tourniquet_action_observed"
        ]
      },
      "label": "Remove tourniquet without indication",
      "origin": "source_template",
      "phase_after": "complete",
      "prerequisites": [
        "receive_handoff"
      ],
      "repeatable": false,
      "required_event_ids": [],
      "source_action_id": "remove_tourniquet",
      "terminal_effect": "failed",
      "wit_category": "unsafe_action"
    }
  ],
  "actors": [
    {
      "actor_id": "receiving_provider",
      "initial_knowledge": [
        "casualty_inbound",
        "prearrival_notice"
      ],
      "role": "Receiving provider"
    },
    {
      "actor_id": "clinic_nurse",
      "initial_knowledge": [
        "casualty_inbound",
        "prearrival_notice"
      ],
      "role": "Clinic nurse"
    },
    {
      "actor_id": "diagnostics_tech",
      "initial_knowledge": [],
      "role": "Diagnostics technician"
    },
    {
      "actor_id": "wit_observer",
      "initial_knowledge": [
        "exercise_started"
      ],
      "role": "Wing Inspection Team process observer"
    }
  ],
  "authority": {
    "automatic_clinical_rule_generation": false,
    "clinical_content_mode": "INHERITED_REPOSITORY_TEMPLATE",
    "deployment_scope": "production_training_reference",
    "evidence_mode": "IDENTITY_AND_SCOPE_ONLY",
    "operational_content_mode": "DETERMINISTIC_EXERCISE_ORCHESTRATION",
    "patient_care_use": "PROHIBITED"
  },
  "canonical_command_sequence": [
    "receive_handoff",
    "primary_assessment",
    "monitor_vitals",
    "differential",
    "order_imaging",
    "order_labs",
    "pain_management",
    "confirm_surge_roles",
    "documentation",
    "wait_for_diagnostics",
    "review_diagnostics",
    "escalation",
    "complete_handoff"
  ],
  "care_continuum_phase": "post_cuf_tfc_facility_reception",
  "completion": {
    "required_event_ids": [
      "prearrival_notice",
      "second_casualty_inbound",
      "diagnostics_ready"
    ],
    "required_operational_actions": [
      "receive_handoff",
      "confirm_surge_roles",
      "wait_for_diagnostics",
      "review_diagnostics",
      "complete_handoff"
    ],
    "required_source_action_priorities": [
      "critical",
      "important"
    ]
  },
  "events": [
    {
      "event_id": "prearrival_notice",
      "knowledge_grants": {
        "clinic_nurse": [
          "prearrival_notice"
        ],
        "receiving_provider": [
          "prearrival_notice"
        ],
        "wit_observer": [
          "prearrival_notification_observed"
        ]
      },
      "label": "Pre-arrival notification received",
      "reveal_source_hidden_findings": false,
      "terminal_effect": null,
      "trigger": {
        "kind": "initial"
      },
      "wit_category": "preparedness"
    },
    {
      "event_id": "second_casualty_inbound",
      "knowledge_grants": {
        "clinic_nurse": [
          "second_casualty_inbound"
        ],
        "receiving_provider": [
          "second_casualty_inbound"
        ],
        "wit_observer": [
          "surge_notice_observed"
        ]
      },
      "label": "Second casualty reported inbound",
      "reveal_source_hidden_findings": false,
      "terminal_effect": null,
      "trigger": {
        "at_elapsed_seconds": 240,
        "kind": "elapsed_time_due"
      },
      "wit_category": "surge_response"
    },
    {
      "event_id": "diagnostics_ready",
      "knowledge_grants": {
        "clinic_nurse": [
          "diagnostic_results_received"
        ],
        "diagnostics_tech": [
          "diagnostic_results_delivered"
        ],
        "receiving_provider": [
          "diagnostic_results_received"
        ],
        "wit_observer": [
          "diagnostic_results_timing_observed"
        ]
      },
      "label": "Ordered imaging and laboratory results are available",
      "reveal_source_hidden_findings": true,
      "terminal_effect": null,
      "trigger": {
        "kind": "diagnostics_due"
      },
      "wit_category": "diagnostics"
    },
    {
      "event_id": "timeout_reached",
      "knowledge_grants": {
        "wit_observer": [
          "timeout_observed"
        ]
      },
      "label": "Source-bound exercise timeout reached",
      "reveal_source_hidden_findings": false,
      "terminal_effect": "timeout",
      "trigger": {
        "kind": "timeout_due"
      },
      "wit_category": "timeliness"
    }
  ],
  "example_id": "ASK-FACILITY-ARRIVAL-RC3-3",
  "parameters": {
    "diagnostic_delay_seconds": {
      "calibration_status": "NOT_CALIBRATED",
      "note": "Deterministic exercise-design delay after both diagnostic orders; not a real-world turnaround estimate.",
      "origin": "exercise_assumption",
      "unit": "seconds",
      "value": 180
    },
    "pass_threshold_bps": {
      "calibration_status": "NOT_CALIBRATED",
      "note": "Reference training threshold; not a validated learner-outcome threshold.",
      "origin": "exercise_policy",
      "unit": "basis_points",
      "value": 8000
    },
    "timeout_seconds": {
      "calibration_status": "SOURCE_BOUND",
      "note": "Inherited from ASK-D-001 end_conditions.timeout_minutes.",
      "origin": "source_template",
      "unit": "seconds",
      "value": 1200
    }
  },
  "profile_id": "BASE_CLINIC_TRAUMA_RECEPTION_RC3_3",
  "schema_version": "1.1.0",
  "sequence_assurance": {
    "selected_three_event_sequences": [
      [
        "prearrival_notice",
        "receive_handoff",
        "primary_assessment"
      ],
      [
        "order_imaging",
        "order_labs",
        "diagnostics_ready"
      ],
      [
        "order_labs",
        "order_imaging",
        "diagnostics_ready"
      ],
      [
        "second_casualty_inbound",
        "confirm_surge_roles",
        "complete_handoff"
      ],
      [
        "diagnostics_ready",
        "review_diagnostics",
        "escalation"
      ],
      [
        "review_diagnostics",
        "documentation",
        "complete_handoff"
      ],
      [
        "wait_60",
        "timeout_reached",
        "timeout"
      ]
    ]
  },
  "source_scenario_id": "ASK-D-001",
  "title": "Post-CUF/TFC blast casualty reception at a constrained base clinic"
} as FacilityArrivalSpec;
