#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path, PurePath, PurePosixPath
from typing import Any

REGISTRY = Path('public/data/content_registry/content_registry.json')
SCENARIO_SOURCE = Path('src/content/scenarios.ts')
TARGET = Path('src/facility-arrival/bindings.generated.ts')
BINDING_JSON = Path('config/facility-arrival/source-binding.generated.json')
SOURCE_PROJECTION_SHA256 = 'b5562e64b4847d7bc47afc9fcc1e917aeee3268dddee3134bd2c3129266d5636'
REPORT = Path('reports/facility-arrival-bindings.json')
SOURCE_HASH_MODE = 'canonical_utf8_lf_v1'
PATH_MODE = 'repository_posix_v1'


class BindingError(ValueError):
    pass


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def canonical_utf8_lf_bytes(path: Path) -> bytes:
    raw = path.read_bytes()
    if raw.startswith(b'\xef\xbb\xbf'):
        raise BindingError(f'UTF-8 BOM forbidden:{canonical_repo_path(path)}')
    try:
        text = raw.decode('utf-8')
    except UnicodeDecodeError as exc:
        raise BindingError(f'non-UTF-8 source:{canonical_repo_path(path)}:{exc}') from exc
    return text.replace('\r\n', '\n').replace('\r', '\n').encode('utf-8')


def sha256_canonical_text(path: Path) -> str:
    return hashlib.sha256(canonical_utf8_lf_bytes(path)).hexdigest()


def canonical(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=False)


def canonical_repo_path(path: PurePath) -> str:
    """Serialize a repository-relative path identically on every host OS.

    pathlib.Path.__str__ follows the host platform, so a Windows checkout turns
    ``src/content/scenarios.ts`` into ``src\\content\\scenarios.ts``. Repository
    manifests, registries, attestations, and generated JSON instead use a
    canonical POSIX representation. This function is the only serializer used
    at the binding boundary.
    """

    raw = path.as_posix()
    pure = PurePosixPath(raw)
    if not raw or raw in {'.', '/'}:
        raise BindingError('empty repository path forbidden')
    if pure.is_absolute() or '..' in pure.parts:
        raise BindingError(f'unsafe repository path:{raw}')
    if '\\' in raw:
        raise BindingError(f'noncanonical repository separator:{raw}')
    return raw


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--repo', type=Path, default=Path('.'))
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    repo = args.repo.resolve()
    errors: list[str] = []

    registry_path = canonical_repo_path(REGISTRY)
    scenario_source_path = canonical_repo_path(SCENARIO_SOURCE)
    target_path = canonical_repo_path(TARGET)
    binding_json_repo_path = canonical_repo_path(BINDING_JSON)

    try:
        registry = json.loads((repo / REGISTRY).read_text(encoding='utf-8'))
        roots = registry.get('roots')
        if not isinstance(roots, dict) or not isinstance(roots.get('registry_merkle_root'), str):
            raise BindingError('registry root missing')
        assets = registry.get('assets')
        if not isinstance(assets, list):
            raise BindingError('registry assets missing')
        matches = [asset for asset in assets if asset.get('asset_id') == 'template:ASK-D-001']
        if len(matches) != 1:
            raise BindingError('ASK-D-001 template asset must appear exactly once')
        asset = matches[0]
        if asset.get('kind') != 'protected_template':
            raise BindingError('ASK-D-001 asset kind differs')
        source = asset.get('source')
        if not isinstance(source, dict) or source.get('path') != scenario_source_path:
            raise BindingError('ASK-D-001 source path differs')
        source_digest = sha256_canonical_text(repo / SCENARIO_SOURCE)
        if source.get('file_sha256') != source_digest:
            raise BindingError('ASK-D-001 registry source hash differs from repository source')
        record_digest = asset.get('record_sha256')
        if not isinstance(record_digest, str) or len(record_digest) != 64:
            raise BindingError('ASK-D-001 record hash missing')
        registry_root = roots['registry_merkle_root']
        expected = (
            '/* AUTO-GENERATED by scripts/build_facility_arrival_bindings.py. DO NOT EDIT. */\n'
            f"export const FACILITY_CONTENT_REGISTRY_ROOT = '{registry_root}' as const;\n"
            f"export const FACILITY_TEMPLATE_RECORD_SHA256 = '{record_digest}' as const;\n"
            f"export const FACILITY_SCENARIO_SOURCE_SHA256 = '{source_digest}' as const;\n"
            f"export const FACILITY_SCENARIO_SOURCE_HASH_MODE = '{SOURCE_HASH_MODE}' as const;\n"
            f"export const FACILITY_SOURCE_SCENARIO_PROJECTION_SHA256 = '{SOURCE_PROJECTION_SHA256}' as const;\n"
        )
        binding_payload = {
            'schema_version': '1.0.0',
            'source_scenario_id': 'ASK-D-001',
            'source_scenario_projection_sha256': SOURCE_PROJECTION_SHA256,
            'scenario_source_path': scenario_source_path,
            'scenario_source_sha256': source_digest,
            'scenario_source_hash_mode': SOURCE_HASH_MODE,
            'template_asset_id': 'template:ASK-D-001',
            'template_record_sha256': record_digest,
            'content_registry_merkle_root': registry_root,
        }
        binding_json_text = json.dumps(binding_payload, indent=2, sort_keys=True) + '\n'
        target = repo / TARGET
        binding_json_path = repo / BINDING_JSON
        if args.check:
            if not target.is_file() or target.read_text(encoding='utf-8') != expected:
                errors.append(target_path)
            if not binding_json_path.is_file() or binding_json_path.read_text(encoding='utf-8') != binding_json_text:
                errors.append(binding_json_repo_path)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding='utf-8', newline='\n')
            binding_json_path.parent.mkdir(parents=True, exist_ok=True)
            binding_json_path.write_text(binding_json_text, encoding='utf-8', newline='\n')
        report = {
            'schema_version': '1.1.0',
            'status': 'PASS' if not errors else 'FAIL',
            'mode': 'check' if args.check else 'write',
            'attestation_kind': 'verification' if args.check else 'generation',
            'registry_path': registry_path,
            'registry_file_sha256': sha256_file(repo / REGISTRY),
            'registry_merkle_root': registry_root,
            'scenario_source_path': scenario_source_path,
            'scenario_source_sha256': source_digest,
            'scenario_source_raw_sha256': sha256_file(repo / SCENARIO_SOURCE),
            'scenario_source_hash_mode': SOURCE_HASH_MODE,
            'target_path': target_path,
            'target_file_sha256': sha256_file(target) if target.is_file() else None,
            'binding_json_path': binding_json_repo_path,
            'binding_json_file_sha256': sha256_file(binding_json_path) if binding_json_path.is_file() else None,
            'template_record_sha256': record_digest,
            'binding_sha256': hashlib.sha256(canonical({
                'registry_merkle_root': registry_root,
                'template_record_sha256': record_digest,
                'scenario_source_sha256': source_digest,
                'scenario_source_hash_mode': SOURCE_HASH_MODE,
            }).encode('utf-8')).hexdigest(),
            'mismatches': errors,
        }
        attested = dict(report)
        report['attestation_sha256'] = hashlib.sha256(canonical(attested).encode('utf-8')).hexdigest()
    except (OSError, json.JSONDecodeError, BindingError, KeyError, TypeError) as exc:
        report = {
            'schema_version': '1.1.0',
            'status': 'FAIL',
            'mode': 'check' if args.check else 'write',
            'attestation_kind': 'verification' if args.check else 'generation',
            'errors': [str(exc)],
        }
    # Only check mode writes the durable verification attestation. Repeated
    # generation during production builds cannot downgrade it to write mode.
    if args.check:
        output = repo / REPORT
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n', encoding='utf-8', newline='\n')
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report.get('status') == 'PASS' else 1


if __name__ == '__main__':
    raise SystemExit(main())
