import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const repoArg=process.argv.indexOf('--repo'); const repo=resolve(repoArg>=0?process.argv[repoArg+1]:'.');
const outArg=process.argv.indexOf('--output'); const output=resolve(repo,outArg>=0?process.argv[outArg+1]:'reports/facility-decision-artifacts-node.json');
const base=resolve(repo,'examples/facility-decision'); const errors=[]; let checks=0;
const check=(condition,message)=>{checks+=1;if(!condition)errors.push(message)};
const json=(name)=>JSON.parse(readFileSync(resolve(base,name),'utf8'));
const shaBytes=(value)=>createHash('sha256').update(value).digest('hex');
function canonical(value){if(value===null)return'null';if(typeof value==='string'||typeof value==='boolean')return JSON.stringify(value);if(typeof value==='number'){if(!Number.isFinite(value))throw new Error('nonfinite');return Object.is(value,-0)?'0':JSON.stringify(value)}if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(typeof value!=='object')throw new Error('unsupported');return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonical(value[k])}`).join(',')}}`}
const shaObj=(value)=>shaBytes(Buffer.from(canonical(value),'utf8'));
function keys(value,out=new Set()){if(Array.isArray(value))value.forEach(v=>keys(v,out));else if(value&&typeof value==='object')Object.entries(value).forEach(([k,v])=>{out.add(k);keys(v,out)});return out}
function verifySession(session,label){const body={...session};delete body.decision_root_sha256;check(session.decision_root_sha256===shaObj(body),`${label}:decision root`);let prior=shaObj([]);const submissions=new Map(session.submissions.map(x=>[x.submission_id,x]));session.decision_records.forEach((record,index)=>{check(record.sequence===index+1,`${label}:sequence:${index+1}`);check(record.prior_record_sha256===prior,`${label}:predecessor:${index+1}`);const body={...record};delete body.record_sha256;check(record.record_sha256===shaObj(body),`${label}:record hash:${index+1}`);check(record.payload_sha256===shaObj(submissions.get(record.submission_id)),`${label}:payload:${index+1}`);prior=record.record_sha256});check(session.decision_chain_root_sha256===prior,`${label}:chain`);check(session.facility_session.final_state.terminal_status==='completed',`${label}:terminal`);check(session.facility_session.normalized_score_bps===10000,`${label}:score`);check(session.handoff.responsibility_transferred_at_seconds!==null,`${label}:handoff`)}
try{
 const manifest=json('manifest.json'); const manifestBody={...manifest};delete manifestBody.manifest_binding_sha256;check(manifest.manifest_binding_sha256===shaObj(manifestBody),'manifest binding');
 Object.entries(manifest.files).forEach(([name,meta])=>{const p=resolve(base,name);check(existsSync(p),`file missing:${name}`);if(existsSync(p)){const data=readFileSync(p);check(data.length===meta.bytes,`file bytes:${name}`);check(shaBytes(data)===meta.sha256,`file hash:${name}`)}});
 const canonicalSession=json('reference-session.json'); const alternate=json('alternate-session.json');verifySession(canonicalSession,'canonical');verifySession(alternate,'alternate');check(canonicalSession.decision_root_sha256===manifest.canonical_decision_root_sha256,'canonical binding');check(alternate.decision_root_sha256===manifest.alternate_decision_root_sha256,'alternate binding');check(JSON.stringify(canonicalSession.submissions.map(x=>x.decision_id))===JSON.stringify(manifest.canonical_sequence),'canonical sequence');check(JSON.stringify(alternate.submissions.map(x=>x.decision_id))===JSON.stringify(manifest.alternate_sequence),'alternate sequence');check(JSON.stringify(manifest.canonical_sequence)!==JSON.stringify(manifest.alternate_sequence),'sequences collapsed');
 const restricted=new Set(['instructor','demo','normalized_source_score_bps','source_binding','facility_certificate','wit_observations','profile_authority','source_action_id','source_origin','autoplay_available','completed_replay_available','branch_controls','high_risk','must_equal','required_values']);
 for(const [name,mode] of Object.entries({'learner-projection.json':'learner_assessment','teaching-projection.json':'learner_teaching','instructor-projection.json':'instructor','demo-projection.json':'stakeholder_demo'})){const view=json(name);check(view.ui_mode===mode,`mode:${name}`);const observed=keys(view);if(mode.startsWith('learner_'))check([...restricted].every(k=>!observed.has(k)),`learner leakage:${name}`);if(mode==='instructor')check(view.instructor&& !view.demo,'instructor boundary');if(mode==='stakeholder_demo')check(view.instructor&&view.demo,'demo boundary')}
 check(manifest.authority.patient_care_use==='PROHIBITED','patient-care escalation');check(manifest.authority.concrete_treatment_activation===false,'treatment escalation');
 const readme=readFileSync(resolve(base,'README.md'),'utf8');
 for(const route of ['/examples/facility-decision/learner','/examples/facility-decision/teaching','/examples/facility-decision/instructor','/examples/facility-decision/demo']) check(readme.includes(route),`README route:${route}`);
}catch(error){errors.push(`internal:${error instanceof Error?error.message:String(error)}`)}
const report={schema_version:'1.0.0',status:errors.length?'FAIL':'PASS',checks,internal_error:false,errors:[...new Set(errors)].sort()};mkdirSync(dirname(output),{recursive:true});writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(errors.length)process.exit(1);
