#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { lstatSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, resolve, sep } from 'node:path';
const CONFIG='config/release/PLAIN_LANGUAGE_CHANGE_SUMMARY.json';
const HEADINGS=['What changed?','What can a learner do now?','What can an instructor do now?','What changed in scenario variety?','What changed in scoring?','What changed in treatment content?','What safety limitation remains?','What is still not calibrated or validated?'];
const KEYS=['what_changed','learner_gain','instructor_gain','scenario_variety','scoring_change','treatment_change','safety_limitations','not_calibrated_or_validated'];
const FORBIDDEN=['clinically validated','patient care ready','realistic clinical timing','this is a validated proficiency score','treatment recommendation','debt-free','zero risk'];
function args(argv){const r={repo:'.',jsonOutput:'reports/plain-language-change-summary-node.json'};for(let i=0;i<argv.length;i++){if(argv[i]==='--repo')r.repo=argv[++i];else if(argv[i]==='--json-output')r.jsonOutput=argv[++i];else throw new Error(`unknown argument:${argv[i]}`);}return r;}
function canonical(v){if(v===null||typeof v==='string'||typeof v==='boolean')return JSON.stringify(v);if(typeof v==='number'){if(!Number.isSafeInteger(v))throw new Error('non-integer canonical number');return JSON.stringify(v);}if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;throw new Error('unsupported canonical value');}
const sha=v=>createHash('sha256').update(canonical(v),'utf8').digest('hex');
function safe(root,v,label){if(typeof v!=='string'||!v||v.includes('\0')||v.includes('\\')||isAbsolute(v))throw new Error(`unsafe repository path:${label}`);const parts=v.split('/');if(parts.some(p=>!p||p==='.'||p==='..'||p.includes(':')||p.endsWith(' ')||p.endsWith('.')))throw new Error(`unsafe repository path:${label}`);const c=resolve(root,...parts),prefix=root.endsWith(sep)?root:`${root}${sep}`;if(c!==root&&!c.startsWith(prefix))throw new Error(`repository path escapes root:${label}`);return c;}
function read(path){const s=lstatSync(path);if(!s.isFile()||s.isSymbolicLink())throw new Error(`required regular file missing:${path}`);return JSON.parse(readFileSync(path,'utf8'));}
function render(v){const lines=[`# ${v.release_label}`,'',`Summary identity: \`${v.summary_id}\``,'','This document explains the user-facing effect of the release. It does not replace the underlying assurance evidence.',''];for(let i=0;i<HEADINGS.length;i++){lines.push(`## ${HEADINGS[i]}`,'',...v.sections[KEYS[i]].map(x=>`- ${x}`),'');}lines.push('## Permanent authority boundary','','- Healthcare simulation and training are permitted only within the validated scope.','- Direct patient care is prohibited.','- Clinical decision support is prohibited.','- Patient-care authority is none.','- Operational timing is not calibrated.','- Scoring remains source-conformance only and is not a validated proficiency measure.','');return lines.join('\n');}
function write(path,v){mkdirSync(dirname(path),{recursive:true});const t=`${path}.tmp-${process.pid}`;writeFileSync(t,`${JSON.stringify(v,null,2)}\n`,'utf8');renameSync(t,path);}
const errors=[];try{const a=args(process.argv.slice(2)),root=resolve(a.repo),v=read(safe(root,CONFIG,'config')),body={...v};delete body.summary_sha256;if(v.summary_sha256!==sha(body))errors.push('plain-language summary self hash differs');if(canonical(v.required_heading_order)!==canonical(HEADINGS))errors.push('plain-language heading order differs from compiled floor');for(const key of KEYS)if(!Array.isArray(v.sections?.[key])||!v.sections[key].length)errors.push(`plain-language section missing:${key}`);const text=Object.values(v.sections??{}).flat().join(' ').toLowerCase();for(const phrase of FORBIDDEN)if(text.includes(phrase))errors.push(`unsupported plain-language claim:${phrase}`);const expected=render(v),observed=readFileSync(safe(root,v.output_path,'output_path'),'utf8');if(observed!==expected)errors.push('plain-language Markdown differs from independent reconstruction');const report={schema_version:'1.0.0',classification:errors.length?'FAIL':'PASS',status:errors.length?'FAIL':'PASS',checker:'INDEPENDENT_NODE_STDLIB_RECONSTRUCTION_V1',summary_id:v.summary_id,headings:HEADINGS.length,sections:KEYS.length,errors};write(safe(root,a.jsonOutput,'json_output'),report);console.log(JSON.stringify(report,null,2));}catch(e){errors.push(e instanceof Error?e.message:String(e));console.log(JSON.stringify({schema_version:'1.0.0',classification:'FAIL',status:'FAIL',checker:'INDEPENDENT_NODE_STDLIB_RECONSTRUCTION_V1',errors},null,2));}process.exit(errors.length?3:0);
