#!/usr/bin/env python3
"""Converge and verify the dependency-independent RC3.8A.1 evolution artifacts.

This command exists to make generator ordering a checked contract instead of a
tribal-knowledge procedure. It locks the graph, runs each canonical Python
writer in dependency order, relocks generated bytes, and then runs independent
Python and Node verification. Unexpected locked-source writes fail closed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import stat
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

sys.dont_write_bytecode = True

from release_graph_core import GRAPH_PATH, write_json
from release_result import FAIL, INTERNAL_ERROR, PASS, exit_code

OUTPUT = Path("reports/engine-evolution-stabilization.json")
PROFILE = "BOUNDED_GRAPH_FIRST_CANONICAL_WRITER_CONVERGENCE_V2"
MAX_ATTEMPTS = 3
COMMAND_TIMEOUT_SECONDS = 240


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _graph_locked_paths(repo: Path) -> set[str]:
    graph = json.loads((repo / GRAPH_PATH).read_text(encoding="utf-8"))
    paths = {GRAPH_PATH.as_posix()}
    for specification in graph.get("input_sets", {}).values():
        paths.update((specification.get("files") or {}).keys())
    return paths


def _repository_file_paths(repo: Path) -> set[str]:
    """Return a pre-write inventory of repository files that may become locked.

    The graph lock can legitimately expand while the stabilizer is running. A
    newly authenticated pre-existing source must not be misclassified as a
    writer mutation merely because it was absent from the *old* lock map. Keep
    a bounded repository inventory before the first lock, then compare the
    union of old and new locked paths against that stable pre-write snapshot.
    """
    excluded_directories = {".git", ".asklepios", "node_modules", "dist", "__pycache__"}
    paths: set[str] = set()
    for directory, names, files in os.walk(repo, topdown=True, followlinks=False):
        names[:] = sorted(name for name in names if name not in excluded_directories)
        base = Path(directory)
        for name in sorted(files):
            path = base / name
            try:
                relative = path.relative_to(repo).as_posix()
            except ValueError:
                continue
            paths.add(relative)
        for name in names:
            path = base / name
            if path.is_symlink():
                try:
                    paths.add(path.relative_to(repo).as_posix())
                except ValueError:
                    pass
    return paths


def _inventory(repo: Path, paths: set[str]) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for relative in sorted(paths):
        path = repo / relative
        if path.is_symlink():
            result[relative] = {"kind": "symlink", "target": os.readlink(path)}
        elif path.is_file():
            info = path.stat()
            result[relative] = {
                "kind": "file",
                "bytes": info.st_size,
                "mode": stat.S_IMODE(info.st_mode),
                "sha256": _sha256(path),
            }
        else:
            result[relative] = {"kind": "missing"}
    return result


def _allowed_generated_path(relative: str) -> bool:
    exact = {
        GRAPH_PATH.as_posix(),
        "README.md",
        "docs/FACILITY_ARRIVAL_STANDALONE.md",
        "examples/verified-scenario/README.md",
        "examples/verified-scenario/manifest.json",
        "public/data/scenario_core/offline_scenario_release.json",
        "public/data/scenario_core/verified_scenario_genome.json",
    }
    prefixes = (
        "examples/facility-arrival/",
        "public/data/facility_arrival/",
        "reports/",
    )
    return relative in exact or relative.startswith(prefixes)


def _atomic_report(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            json.dump(value, stream, indent=2, sort_keys=True)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _command(repo: Path, command: list[str], canonical: list[str]) -> dict[str, Any]:
    started = time.monotonic()
    environment = os.environ.copy()
    environment.update({"PYTHONDONTWRITEBYTECODE": "1", "PYTHONUTF8": "1", "TZ": "UTC"})
    try:
        completed = subprocess.run(
            command,
            cwd=repo,
            env=environment,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            timeout=COMMAND_TIMEOUT_SECONDS,
        )
        return {
            "command": canonical,
            "classification": PASS if completed.returncode == 0 else FAIL,
            "returncode": completed.returncode,
            "stdout_tail": completed.stdout.splitlines()[-40:],
            "stderr_tail": completed.stderr.splitlines()[-40:],
            "duration_ms": int((time.monotonic() - started) * 1000),
        }
    except subprocess.TimeoutExpired as exc:
        return {
            "command": canonical,
            "classification": INTERNAL_ERROR,
            "returncode": 4,
            "stdout_tail": (exc.stdout or "").splitlines()[-40:] if isinstance(exc.stdout, str) else [],
            "stderr_tail": (exc.stderr or "").splitlines()[-40:] if isinstance(exc.stderr, str) else [],
            "duration_ms": int((time.monotonic() - started) * 1000),
            "errors": [f"command timeout after {COMMAND_TIMEOUT_SECONDS}s"],
        }


def _python(repo: Path, script: str, *arguments: str) -> tuple[list[str], list[str]]:
    return [sys.executable, script, *arguments], ["python", script, *arguments]


def _node(script: str, *arguments: str) -> tuple[list[str], list[str]]:
    executable = shutil.which("node")
    if not executable:
        raise RuntimeError("Node executable unavailable")
    return [executable, script, *arguments], ["node", script, *arguments]


def _write_commands(repo: Path) -> list[tuple[list[str], list[str]]]:
    return [
        _python(repo, "scripts/lock_release_graph.py", "--repo", "."),
        _python(repo, "scripts/build_scenario_genome.py", "--repo", ".", "--json-output", "reports/scenario-genome.json"),
        _python(repo, "scripts/build_facility_arrival_example.py", "--repo", ".", "--output", "reports/facility-arrival-python-build.json"),
        _python(repo, "scripts/build_verified_example_scenario.py", "--repo", ".", "--report", "reports/verified-example-generation.json"),
        _python(repo, "scripts/build_facility_arrival_standalone.py", "--repo", "."),
        _python(repo, "scripts/build_offline_scenario_release.py", "--repo", ".", "--json-output", "reports/offline-scenario-release.json"),
        _python(repo, "scripts/lock_release_graph.py", "--repo", "."),
    ]


def _check_commands(repo: Path) -> list[tuple[list[str], list[str]]]:
    return [
        _python(repo, "scripts/lock_release_graph.py", "--repo", ".", "--check"),
        _python(repo, "scripts/check_release_graph.py", "--repo", ".", "--json-output", "reports/release-graph-consistency.json"),
        _python(repo, "scripts/build_scenario_genome.py", "--repo", ".", "--check", "--json-output", "reports/scenario-genome-python-check.json"),
        _node("scripts/check_scenario_genome.mjs", "--repo", ".", "--report", "reports/scenario-genome-node.json"),
        _python(repo, "scripts/build_facility_arrival_example.py", "--repo", ".", "--check", "--output", "reports/facility-arrival-example-check.json"),
        _python(repo, "scripts/build_verified_example_scenario.py", "--repo", ".", "--check", "--report", "reports/verified-example-generation-check.json"),
        _python(repo, "scripts/build_facility_arrival_standalone.py", "--repo", ".", "--check"),
        _python(repo, "scripts/build_offline_scenario_release.py", "--repo", ".", "--check", "--json-output", "reports/offline-scenario-release-check.json"),
        _node("scripts/check_offline_scenario_release.mjs", "--repo", ".", "--json-output", "reports/offline-scenario-release-node.json"),
        _python(repo, "scripts/check_engine_evolution_documentation.py", "--repo", ".", "--json-output", "reports/scenario-engine-evolution-docs-python.json"),
        _node("scripts/check_engine_evolution_documentation.mjs", "--repo", ".", "--json-output", "reports/scenario-engine-evolution-docs-node.json"),
    ]


def run(repo: Path, *, check_only: bool) -> dict[str, Any]:
    repo = repo.resolve(strict=True)
    locked_paths_before = _graph_locked_paths(repo)
    repository_paths_before = _repository_file_paths(repo)
    repository_inventory_before = _inventory(repo, repository_paths_before | locked_paths_before)
    attempts: list[dict[str, Any]] = []
    classification = FAIL
    errors: list[str] = []

    for attempt_number in range(1, 2 if check_only else MAX_ATTEMPTS + 1):
        records: list[dict[str, Any]] = []
        if not check_only:
            for command, canonical in _write_commands(repo):
                record = _command(repo, command, canonical)
                records.append(record)
                if record["classification"] != PASS:
                    break
        if not records or records[-1]["classification"] == PASS:
            for command, canonical in _check_commands(repo):
                record = _command(repo, command, canonical)
                records.append(record)
                if record["classification"] != PASS:
                    break
        attempt_classification = PASS if records and all(item["classification"] == PASS for item in records) else FAIL
        attempts.append({"attempt": attempt_number, "classification": attempt_classification, "commands": records})
        if attempt_classification == PASS:
            classification = PASS
            break
        if check_only:
            break

    locked_paths_after = _graph_locked_paths(repo)
    comparison_paths = locked_paths_before | locked_paths_after
    inventory_before = {
        relative: repository_inventory_before.get(relative, {"kind": "missing"})
        for relative in comparison_paths
    }
    inventory_after = _inventory(repo, comparison_paths)
    changed = sorted(
        relative
        for relative in set(inventory_before) | set(inventory_after)
        if inventory_before.get(relative) != inventory_after.get(relative)
    )
    unexpected = [relative for relative in changed if not _allowed_generated_path(relative)]
    if unexpected:
        classification = FAIL
        errors.extend(f"canonical evolution writer modified unauthorized locked source:{relative}" for relative in unexpected)
    if classification != PASS and not errors:
        errors.append("engine-evolution artifacts did not converge within the bounded attempt budget")

    return {
        "schema_version": "1.0.0",
        "classification": classification,
        "status": classification,
        "profile": PROFILE,
        "mode": "check" if check_only else "write",
        "attempt_limit": 1 if check_only else MAX_ATTEMPTS,
        "attempts": attempts,
        "locked_paths_before": len(locked_paths_before),
        "locked_paths_after": len(locked_paths_after),
        "changed_locked_paths": changed,
        "unexpected_locked_source_writes": unexpected,
        "errors": errors,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path("."))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--json-output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    try:
        result = run(args.repo, check_only=args.check)
    except Exception as exc:  # noqa: BLE001
        result = {
            "schema_version": "1.0.0",
            "classification": INTERNAL_ERROR,
            "status": INTERNAL_ERROR,
            "profile": PROFILE,
            "mode": "check" if args.check else "write",
            "errors": [f"{type(exc).__name__}:{exc}"],
        }
    output = args.repo.resolve() / args.json_output
    _atomic_report(output, result)
    print(json.dumps(result, indent=2, sort_keys=True))
    return exit_code(result["classification"])


if __name__ == "__main__":
    raise SystemExit(main())
